services:
  backend:
    image: registry.gitlab.com/phanminhkaneki/js-realtime-chat/backend:${BACKEND_TAG:-latest}
    container_name: chat-backend
    restart: unless-stopped
    env_file:
      - .env # file .env được Jenkins scp sang trước đó
    ports:
      - "3000:3000"

  frontend:
    image: registry.gitlab.com/phanminhkaneki/js-realtime-chat/frontend:${FRONTEND_TAG:-latest}
    container_name: chat-frontend
    restart: unless-stopped
    ports:
      - "80:80"
